version: "3"

services:
  pgvector:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embeddings
    volumes:
      - pgvectordata:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  lanterndb:
    image: lanterndata/lantern:latest-pg15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embeddings
    volumes:
      - lanterndata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  
  qdrant-database:
    image: qdrant/qdrant:v1.3.2
    environment:
      - QDRANT__SERVICE__API_KEY=qdrant_pass
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgvectordata:
  lanterndata:
  qdrant_data:
